# Generated by Django 4.2.2 on 2023-06-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_movie_utube_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="utube_link", new_name="utube",
        ),
    ]
